### PR TITLE
Create composite key for attendance

### PR DESCRIPTION
**Pull request by riencus**
Attendance Model only use NIK as its Primary Key---which is false. Since this would means each employee only has one attendance record.

This Pull Request create composite PK using NIK and Date---like what a Attendance record should be.
Also change all file affected by this change.

### CODE REVIEW

**Review by riencus — COMMENTED** [review]
on second thought, I think I should include a unit test in this pull request

**Review by sebastianbagya — APPROVED** [review]

**Comment by sebastianbagya** [comment]
> on second thought, I think I should include a unit test in this pull request
< Ok!

**Comment by riencus** [comment]
@sebastianbagya, Please take look at my newest commit.
I need your help

**Comment by sebastianbagya** [comment]
@arielchristianto, Ok. I will take a look of it after class, its about 30 - 60 min later.

**Review by aamesaa — APPROVED** [review]

**Pull request merged**
